# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)
favicon: images/favicon.ico

# Personal info
name: KAMIL ANINDITA
title: Interested in Programming and Networking
email: kamilanindita@gmail.com
#phone: Your phone number (optional)
#website: Your website (eg. https://google.com)(optional)

darkmode: false

# Social links
twitter_username: kamilanindita28
github_username:  kamilanindita
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
facebook_username: kamilanindita
#flickr_username: jekyll
instagram_username: kamilanindita
linkedin_username: kamil-anindita-390452189
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: kamilanindita
#googleplus_username: +jekyll
#orcid_username: 0000-0000-0000-0000


# Additional icon links
#additional_links:
#- title: Link name
#  icon: Font Awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Kamil and I am student of Internet Engineering Technology in Gadjah Mada University. I am very interested in  <mark>Programming</mark> and  <mark>Networking</mark>. As well as Network Engineer, I also have experience in Web Developer.<br><br>
  I have skills in <mark>Network Engineer</mark> such as Network Architecture, Network Configuration, Network Throubleshooting and <mark>Backend Web Programming</mark> in various programming languages such as PHP, Javascript, Python, Java, Go, and Ruby.
# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and programming some of my other interests and hobbies are:
  - Football and Futsal
  - Traveling

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
